name: CI

on:
  push:
    branches:
      - main

  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: setup node
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: lts/*

      - name: install
        run: pnpm install --frozen-lockfile

      - name: build
        run: pnpm build

      - name: lint
        run: pnpm lint

      - name: typecheck
        run: pnpm typecheck

  test:
    name: "test (os: ${{ matrix.os }}, node: ${{ matrix.node }}, esbuild: ${{ matrix.esbuild }})"
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        node: [22, 20, 18]
        esbuild: [latest, 0.23.0, 0.21.4, 0.19.2]
        os:
          - ubuntu-latest
          - macos-latest
          - windows-latest
      fail-fast: false
    steps:
      - uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
        with:
          persist-credentials: false

      - name: setup pnpm
        uses: pnpm/action-setup@fe02b34f77f8bc703788d5817da081398fad5dd2 # v4.0.0

      - name: setup node ${{ matrix.node }}
        uses: actions/setup-node@1d0ff469b7ec7b3cb9d8673fde0c81c44821de2a # v4.2.0
        with:
          node-version: ${{ matrix.node }}

      - name: install
        run: pnpm install --frozen-lockfile

      - name: install esbuild ${{ matrix.esbuild }}
        run: pnpm add -D esbuild@${{ matrix.esbuild }}

      - name: build
        run: pnpm build

      - name: test
        run: pnpm test
