name: Test Build Tools

on:
  workflow_dispatch:
  schedule:
    # every sunday at 00:00
    - cron: "0 0 * * 0"

permissions: {}

jobs:
  test-build-tools:
    permissions:
      contents: read
    strategy:
      fail-fast: false
      matrix:
        tool:
          - { name: "esbuild", version: "latest" }
          - { name: "esbuild", version: "0.28.0" }
          - { name: "esbuild", version: "0.25.0" }
          - { name: "esbuild", version: "0.23.0" }
          - { name: "esbuild", version: "0.21.4" }
    uses: luxass/shared-workflows/.github/workflows/reusable-test-build-tools.yaml@a80d13d310b91d509547203435ad21b68ae47ba1 # v0.12.0
    with:
      tool-name: ${{ matrix.tool.name }}
      tool-version: ${{ matrix.tool.version }}
